{
  "formatVersion": "1.1",
  "component": {
    "group": "com.beggar.hotfix",
    "module": "hotfix-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kgzg6ji2urfhvkxksai5iwt3aq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hotfix-base-1.0.0.jar",
          "url": "hotfix-base-1.0.0.jar",
          "size": 3918,
          "sha512": "14de33cc5f382dfcadd16811e543abf6a1e15b860804a875c801df36e65468079777caddca59f21f8fc194323a1781cbc0f4c22dbaa469e05ae87b31b2ae2a92",
          "sha256": "015b9a02556bdcb456a7ea4c19a9e7d972d02212b7e3af1261718772e601d8d4",
          "sha1": "3742285d96238bcc1a7ca4f3e6527e36b51cb9a8",
          "md5": "6572b7f383b49db916e7cae834659fb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hotfix-base-1.0.0.jar",
          "url": "hotfix-base-1.0.0.jar",
          "size": 3918,
          "sha512": "14de33cc5f382dfcadd16811e543abf6a1e15b860804a875c801df36e65468079777caddca59f21f8fc194323a1781cbc0f4c22dbaa469e05ae87b31b2ae2a92",
          "sha256": "015b9a02556bdcb456a7ea4c19a9e7d972d02212b7e3af1261718772e601d8d4",
          "sha1": "3742285d96238bcc1a7ca4f3e6527e36b51cb9a8",
          "md5": "6572b7f383b49db916e7cae834659fb4"
        }
      ]
    }
  ]
}
