{
  "formatVersion": "1.1",
  "component": {
    "group": "com.beggar.hotfix",
    "module": "hotfix-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4pk5t3uqhvemfdld4ir5m66sza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hotfix-base-1.0.0.jar",
          "url": "hotfix-base-1.0.0.jar",
          "size": 3514,
          "sha512": "c1fb4789ae5f581f43c27de3d121e1c7a7f303393ae61b71fcd7f3e5d1cc1a35a1ac0d8ed673a46f8b89d8ee487f9d75d94d0326a8fc4efb73ae89e8a6932a69",
          "sha256": "0d036131762ff3b4224a894a56093fde0d863de3586c1a14abaf6bf0c572e3a5",
          "sha1": "8ddcc2c19a61e59b2cb8c1f871c16f3db0641abb",
          "md5": "bde201425fefe4456e7f946f94248e4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hotfix-base-1.0.0.jar",
          "url": "hotfix-base-1.0.0.jar",
          "size": 3514,
          "sha512": "c1fb4789ae5f581f43c27de3d121e1c7a7f303393ae61b71fcd7f3e5d1cc1a35a1ac0d8ed673a46f8b89d8ee487f9d75d94d0326a8fc4efb73ae89e8a6932a69",
          "sha256": "0d036131762ff3b4224a894a56093fde0d863de3586c1a14abaf6bf0c572e3a5",
          "sha1": "8ddcc2c19a61e59b2cb8c1f871c16f3db0641abb",
          "md5": "bde201425fefe4456e7f946f94248e4b"
        }
      ]
    }
  ]
}
