{
  "formatVersion": "1.1",
  "component": {
    "group": "com.beggar.hotfix",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "elcgmrlbq5enjjj5flt2lgcr3i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 23285,
          "sha512": "3058818f462b680222ff988158a747d612b2b38bd4f2823e65cf39ea9e55b1e0ab652bffa6ee792a916fde0d6d9a547fd7071ce7e7b03e6c8255ba924ca9f5b5",
          "sha256": "17737562afd199ae9765dde0af75d7ec6bcd32443832bf6f1aee6d17ea8988dd",
          "sha1": "809fb318340b52deee1cd7ee540c0e6fbc175e46",
          "md5": "4ad7c6b998ec4cfaa99694e2f0abad37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.20.0-GA"
          }
        },
        {
          "group": "com.beggar.hotfix",
          "module": "hotfix-base",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 23285,
          "sha512": "3058818f462b680222ff988158a747d612b2b38bd4f2823e65cf39ea9e55b1e0ab652bffa6ee792a916fde0d6d9a547fd7071ce7e7b03e6c8255ba924ca9f5b5",
          "sha256": "17737562afd199ae9765dde0af75d7ec6bcd32443832bf6f1aee6d17ea8988dd",
          "sha1": "809fb318340b52deee1cd7ee540c0e6fbc175e46",
          "md5": "4ad7c6b998ec4cfaa99694e2f0abad37"
        }
      ]
    }
  ]
}
