{
  "formatVersion": "1.1",
  "component": {
    "group": "com.beggar.hotfix",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "hbyd66cj65b3nh6yqgej3c3vg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 23052,
          "sha512": "33cb5260679c2e935827acaba749f8817cfdd8671268b86651b2caf97b27a13559b8e98f1304b07199461b366f578c5b4f72b74a949a27292d3744149325447f",
          "sha256": "d7ff61a179480723ceb6936c4b8b08ac8099a3e78c03e075e3e205509841263e",
          "sha1": "95a1463471e85402714e1ffe6cee2ebed8bd6fbc",
          "md5": "589176ba13d0a3c54c4ff4b708b02ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.20.0-GA"
          }
        },
        {
          "group": "com.beggar.hotfix",
          "module": "hotfix-base",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 23052,
          "sha512": "33cb5260679c2e935827acaba749f8817cfdd8671268b86651b2caf97b27a13559b8e98f1304b07199461b366f578c5b4f72b74a949a27292d3744149325447f",
          "sha256": "d7ff61a179480723ceb6936c4b8b08ac8099a3e78c03e075e3e205509841263e",
          "sha1": "95a1463471e85402714e1ffe6cee2ebed8bd6fbc",
          "md5": "589176ba13d0a3c54c4ff4b708b02ebf"
        }
      ]
    }
  ]
}
