{
  "formatVersion": "1.1",
  "component": {
    "group": "com.beggar.hotfix",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4ue4r43fkjhkboqt4y7ejopwxa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 22577,
          "sha512": "6702cfcc971fbc68e8d6e30367eb385bb44b8cc09fb76fbf10612a7739d536922d69410e8a3c98fdcb06f596fd92004112ed7f6a4f18904aa2dcad63c09340a2",
          "sha256": "46fc4cff0a9d272db5dd512c183bea868c569f84c521f25358c354e7571d9e8c",
          "sha1": "c9857179970397d2ba58d592780fac96eacb7ba3",
          "md5": "cade0f21b57af400e868873ee51a0868"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.20.0-GA"
          }
        },
        {
          "group": "com.beggar.hotfix",
          "module": "hotfix-base",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 22577,
          "sha512": "6702cfcc971fbc68e8d6e30367eb385bb44b8cc09fb76fbf10612a7739d536922d69410e8a3c98fdcb06f596fd92004112ed7f6a4f18904aa2dcad63c09340a2",
          "sha256": "46fc4cff0a9d272db5dd512c183bea868c569f84c521f25358c354e7571d9e8c",
          "sha1": "c9857179970397d2ba58d592780fac96eacb7ba3",
          "md5": "cade0f21b57af400e868873ee51a0868"
        }
      ]
    }
  ]
}
